from prompts.emails.draft import DRAFT_SYSTEM_PROMPT, DRAFT_USER_PROMPT
from prompts.github.parse import GITHUB_SYSTEM_PROMPT, GITHUB_USER_PROMPT, GITHUB_USER_PROMPT_RULES
from prompts.graph.employer_enrichment import (
    EMPLOYER_GRAPH_SYSTEM_PROMPT,
    EMPLOYER_GRAPH_USER_PROMPT,
)
from prompts.graph.github_enrichment import GITHUB_GRAPH_SYSTEM_PROMPT, GITHUB_GRAPH_USER_PROMPT
from prompts.graph.resume_enrichment import RESUME_GRAPH_SYSTEM_PROMPT, RESUME_GRAPH_USER_PROMPT
from prompts.resume.parse import RESUME_SYSTEM_PROMPT, RESUME_USER_PROMPT, RESUME_USER_PROMPT_RULES

__all__ = [
    "DRAFT_SYSTEM_PROMPT",
    "DRAFT_USER_PROMPT",
    "EMPLOYER_GRAPH_SYSTEM_PROMPT",
    "EMPLOYER_GRAPH_USER_PROMPT",
    "GITHUB_GRAPH_SYSTEM_PROMPT",
    "GITHUB_GRAPH_USER_PROMPT",
    "GITHUB_SYSTEM_PROMPT",
    "GITHUB_USER_PROMPT",
    "GITHUB_USER_PROMPT_RULES",
    "RESUME_GRAPH_SYSTEM_PROMPT",
    "RESUME_GRAPH_USER_PROMPT",
    "RESUME_SYSTEM_PROMPT",
    "RESUME_USER_PROMPT",
    "RESUME_USER_PROMPT_RULES",
]
