from __future__ import annotations

from typing import Any, Protocol

from app.modules.emails.model import EmailDraft, EnqueueResult


class RedisPipeline(Protocol):
    def zremrangebyscore(self, key: str, start: float, end: float) -> Any: ...

    def zcard(self, key: str) -> Any: ...

    def execute(self) -> list[Any]: ...


class RedisClient(Protocol):
    def get(self, key: str) -> str | None: ...

    def set(self, key: str, value: str) -> None: ...

    def rpush(self, key: str, value: str) -> None: ...

    def lrange(self, key: str, start: int, end: int) -> list[str]: ...

    def lrem(self, key: str, count: int, value: str) -> None: ...

    def zadd(self, key: str, mapping: dict[str, float]) -> None: ...

    def expire(self, key: str, seconds: int) -> None: ...

    def pipeline(self) -> RedisPipeline: ...


class RateLimiter(Protocol):
    def allow(self, key: str, *, limit: int, window_seconds: int) -> bool: ...


class EmailDraftQueue(Protocol):
    @property
    def queue_key(self) -> str: ...

    def enqueue(self, draft: EmailDraft) -> EnqueueResult: ...

    def get(self, draft_id: str) -> EmailDraft | None: ...

    def fetch_pending(self, limit: int = 10) -> list[EmailDraft]: ...

    def mark_sent(self, draft_id: str, *, message_id: str | None = None) -> EmailDraft: ...

    def mark_failed(self, draft_id: str, *, error: str) -> EmailDraft: ...
